Getting started with PyTorch - Tensors
================

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [1]:
import torch

<div class="alert alert-info"><h4>Note</h4><p>An uninitialized matrix is declared,
    but does not contain definite known
    values before it is used. When an
    uninitialized matrix is created,
    whatever values were in the allocated
    memory at the time will appear as the initial values.</p></div>



Construct a 5x3 matrix, uninitialized:



In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[-4.1560e+07,  3.0764e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  6.4460e-44],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22],
        [ 4.5828e+30,  1.2121e+04,  7.1846e+22],
        [ 9.2198e-39,  7.0374e+22, -8.9019e+06]])


Construct a randomly initialized matrix:



In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0392, 0.0230, 0.7024],
        [0.2254, 0.0530, 0.9956],
        [0.3746, 0.9283, 0.1818],
        [0.6740, 0.6002, 0.2143],
        [0.5211, 0.4259, 0.2194]])


Construct a matrix filled zeros and of dtype long:



In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1248, -0.9941, -0.4507],
        [-0.0481,  1.8120, -0.5176],
        [ 1.2265,  0.3288, -0.6353],
        [-0.6949,  1.0399, -0.4461],
        [ 0.5440, -1.0139, -0.4855]])


Get its size:



In [7]:
print(x.size())

torch.Size([5, 3])


Addition: syntax 1



In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.1400, -0.2307,  0.3195],
        [ 0.2070,  2.2647,  0.2080],
        [ 1.8051,  1.2457, -0.4194],
        [-0.0876,  1.6792, -0.4254],
        [ 1.0589, -0.1604, -0.0791]])


Addition: syntax 2



In [9]:
print(torch.add(x, y))

tensor([[ 1.1400, -0.2307,  0.3195],
        [ 0.2070,  2.2647,  0.2080],
        [ 1.8051,  1.2457, -0.4194],
        [-0.0876,  1.6792, -0.4254],
        [ 1.0589, -0.1604, -0.0791]])


Addition: providing an output tensor as argument



In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.1400, -0.2307,  0.3195],
        [ 0.2070,  2.2647,  0.2080],
        [ 1.8051,  1.2457, -0.4194],
        [-0.0876,  1.6792, -0.4254],
        [ 1.0589, -0.1604, -0.0791]])


Addition: in-place



In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.1400, -0.2307,  0.3195],
        [ 0.2070,  2.2647,  0.2080],
        [ 1.8051,  1.2457, -0.4194],
        [-0.0876,  1.6792, -0.4254],
        [ 1.0589, -0.1604, -0.0791]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing



In [12]:
print(x)
print(x.size())
print(x[:, 1])
print(x[:, 1].size())

print(x[:, 1] @ x)

print(x[1, :])
print(x[1, :].size())

tensor([[ 1.1248, -0.9941, -0.4507],
        [-0.0481,  1.8120, -0.5176],
        [ 1.2265,  0.3288, -0.6353],
        [-0.6949,  1.0399, -0.4461],
        [ 0.5440, -1.0139, -0.4855]])
torch.Size([5, 3])
tensor([-0.9941,  1.8120,  0.3288,  1.0399, -1.0139])
torch.Size([5])
tensor([-2.0762,  6.4890, -0.6704])
tensor([-0.0481,  1.8120, -0.5176])
torch.Size([3])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [13]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [ ]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-1.8262])
-1.8262145519256592


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations (if the Torch Tensor is on CPU), and changing one will change
the other.

Converting a Torch Tensor to a NumPy Array:



In [ ]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [ ]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [ ]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor:

Changing the np array also changes the Torch tensor.

In [ ]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
